[package]
name = "gameboy"
version = "0.1.0"
authors = ["tpyd <112725276+tpyd@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.24.0"
#pixels = "0.12.0"